// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTFd6lGcIkwN5oiVQGQ-Z4MTeGlBuHM0',
    appId: '1:341678089856:android:7980f4b9c605343fbc2865',
    messagingSenderId: '341678089856',
    projectId: 'cashbook-ea228',
    storageBucket: 'cashbook-ea228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVQ1gYwNaUXpJdic71ONOobJhEx_jw4d8',
    appId: '1:341678089856:ios:02389e373f8a9c57bc2865',
    messagingSenderId: '341678089856',
    projectId: 'cashbook-ea228',
    storageBucket: 'cashbook-ea228.appspot.com',
    iosClientId: '341678089856-tl16s3c9qsbh5si0mabi3l4uube9pfqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
